RabbitMQ module creating colony vhost
QualiNext/terraform pull request #13
Opened 2021-12-07 20:45 UTC by sasha-quali

AB#5846
Part 1 - Terraform module to create colony vhost

2021-12-08 14:13 UTC, stanb-quali requested changes

2021-12-08 14:13 UTC, stanb-quali commented on rabbit-mq-vhost/variables.tf
> +variable "admin_password" {
define with sensitive = true

2021-12-08 14:13 UTC, stanb-quali commented on rabbit-mq-vhost/variables.tf
> +variable "password" {
define with sensitive = true

2021-12-08 14:50 UTC, sasha-quali commented on rabbit-mq-vhost/variables.tf
> +variable "password" {
Done

2021-12-21 10:16 UTC, stanb-quali approved these changes

2021-12-21 10:20 UTC, merged